pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'python3 -m py_compile sources/add2vals.py sources/calc.py'
                // stash(name: 'compiled-results', includes: 'sources/*.py*')
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                apt-get update && apt-get install -y python3-pip
                python3 -m pip install --upgrade pip --break-system-packages
                python3 -m pip install pytest --break-system-packages
                '''
            }
        }

        stage('Test') {
            steps {
                sh 'pytest --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('CodeScanning'){

            environment {
                SONAR_HOME = tool name: 'sonar-scan' 
            }

            steps {
                withSonarQubeEnv('sonar-qube'){
                    sh '''$SONAR_HOME/bin/sonar-scanner \
                        -Dsonar.projectKey=APP \
                        -Dsonar.projectName=pyinstallerapp \
                        -Dsonar.projectVersion=1.0 \
                        -Dsonar.sources=. \
                        -Dsonar.sourceEncoding=UTF-8
                    '''
                }


            }
        }

        stage('CheckQualityGate'){

            steps {

                timeout(time: 60, unit: 'SECONDS') {
                    waitForQualityGate  abortPipeline: true
                }
            }
        }

        stage('UploadArtifacts') {
            steps {
                script {
                    // Archive the Python source code into a tar.gz file
                    def artifactFile = "python-app-${BUILD_NUMBER}.tar.gz"
                    sh "tar -czf ${artifactFile} sources/*.py"

                    // Upload to Nexus
                    nexusArtifactUploader(
                        nexusVersion: 'nexus3',
                        protocol: 'http',
                        nexusUrl: 'nexus:8081',
                        groupId: 'com.example',
                        version: BUILD_NUMBER,
                        repository: 'python-app',
                        credentialsId: 'nexus-creds',
                        artifacts: [
                            [
                                artifactId: 'python-app',
                                classifier: '',
                                file: artifactFile,
                                type: 'tar.gz'
                            ]
                        ]
                    )
                }
            }
        }


        
    }
}